# ============================================================================
# GitLab CI/CD Stages
# Определение этапов pipeline для деплоя Corax на ALT Linux
# ============================================================================

stages:
  - config_generation    # Генерация конфигурационных файлов
  - terraform            # Применение Terraform конфигурации
  - node_preparation     # Подготовка деплой ноды
 #-
 #-
 #- lvm 
  - jam